name: dart_command
description: "Package to create commands for command pattern"
version: 1.1.0
homepage: https://github.com/TercyoStorck/command

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0